import type { Metadata } from "next";
import localFont from "next/font/local";
import { getServerSession } from "next-auth";
import "./globals.css";
import Navbar from "@/components/NavBar";
import SideBar from "@/components/SideBar";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { routePaths } from "./routePaths";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publicNavBarOptions = [
  { label: "Home", path: "/" },
  { label: "Login", path: routePaths.login },
  { label: "Register", path: routePaths.register },
];

const userNavBarOptions = [{ label: "Logout", path: routePaths.signOut }];

export const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await getServerSession(authOptions);
  const isLoggedIn = session && session.user;

  const navBarOptions = isLoggedIn ? userNavBarOptions : publicNavBarOptions;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar options={navBarOptions} />
        <div className="flex min-h-screen">
          {isLoggedIn && <SideBar />}
          <main className="flex-1 flex justify-center items-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
