import type { Metadata } from "next";
import localFont from "next/font/local";
import { getServerSession } from "next-auth";
import "./globals.css";
import Navbar from "@/components/NavBar";
import SideBar from "@/components/SideBar";
import { routePaths } from "./routePaths";
import { Toaster } from "react-hot-toast";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publicNavBarOptions = [
  { label: "Login", path: routePaths.login },
  { label: "Register", path: routePaths.register },
];

const userNavBarOptions = [{ label: "Logout", path: routePaths.signOut }];

const sidebarOptions = [
  { label: "Inbox", path: routePaths.inbox },
  { label: "Sent", path: routePaths.sent },
  { label: "Create New Message", path: routePaths.newMessage },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const isLoggedIn = session && session.user;

  const navBarOptions = isLoggedIn ? userNavBarOptions : publicNavBarOptions;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar options={navBarOptions} userEmail={session?.user?.email} />
        <div className="flex min-h-screen">
          {isLoggedIn && <SideBar options={sidebarOptions} />}
          <main className="flex-1 flex justify-center">{children}</main>
          <Toaster position="bottom-right" />
        </div>
      </body>
    </html>
  );
}
