import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publicNavBarOptions = [
  { label: "Home", path: "/" },
  { label: "Login", path: "/auth/login" },
  { label: "Register", path: "/auth/register" },
];

const userNavBarOptions = [
  { label: "Profile", path: "/userProfile" },
  { label: "Logout", path: "/api/auth/signout" },
];

export const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await getServerSession(authOptions);

  const navBarOptions =
    session && session.user ? userNavBarOptions : publicNavBarOptions;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar options={navBarOptions} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
